//=logging.level.root=DEBUG

# Esto fuerza la carga de tu archivo local y permite que sobreescriba las propiedades
spring.config.import=optional:classpath:application-local.properties

# Conexi�n al PostgreSQL local que corre en Docker
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci�n JPA para que Hibernate cree las tablas autom�ticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Forzar a SpringDoc a no usar rutas protegidas si es posible
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Desactivar la validaci�n de seguridad de SpringDoc temporalmente
springdoc.show-login-endpoint=true

jwt.secret=${SEC_KEY}
jwt.expiration-ms=86400000

ai.api.url=http://localhost:8090/v1/chat/completions
ai.api.model=qwen2.5-7b-instruct