// logging.level.root=DEBUG

# Esto fuerza la carga de tu archivo local y permite que sobreescriba las propiedades
spring.config.import=optional:classpath:application-local.properties

# Conexión al PostgreSQL local que corre en Docker
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA para que Hibernate cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Forzar a SpringDoc a no usar rutas protegidas si es posible
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Desactivar la validación de seguridad de SpringDoc temporalmente
springdoc.show-login-endpoint=true