ALTER TABLE routine ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id);
ALTER TABLE routine ADD COLUMN IF NOT EXISTS is_completed BOOLEAN DEFAULT FALSE;
ALTER TABLE routine ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;
